Repository Breaking-Dope/breaking-frontend, pull requests merged in 2022-08, with the labels that each got.

#140 feat: 제보글 상세 페이지 기능 추가
  breaking-front/src/App.js
  breaking-front/src/api/post.js
  breaking-front/src/assets/svg/like.svg
  breaking-front/src/assets/svg/liked.svg
  breaking-front/src/assets/svg/more_arrow.svg
  breaking-front/src/components/Toggle/Toggle.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/usePost.js
  breaking-front/src/hooks/queries/usePostBoughtList.js
  breaking-front/src/hooks/queries/usePostComment.js
  breaking-front/src/hooks/queries/usePostReply.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/dummyData/users.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/Comment.styles.js
  breaking-front/src/pages/Post/units/CommentForm.js
  breaking-front/src/pages/Post/units/CommentForm.styles.js
Labels: ♻️ Refactoring, ✨ Function

#144 feat: profile page 백엔드와 연결 테스트 진행
  breaking-front/src/api/profile.js
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.js
  breaking-front/src/utils/ImageUrlConverter.js
Labels: ✨ Function

#145 fix: 컴포넌트 오류 수정 및 일부 기능 추가
  breaking-front/.storybook/preview.js
  breaking-front/src/api/post.js
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.styles.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/Toggle/Toggle.js
  breaking-front/src/components/Toggle/Toggle.stories.js
  breaking-front/src/components/Toggle/Toggle.styles.js
  breaking-front/src/hooks/queries/usePostReply.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Carousel.styles.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/Comment.styles.js
  breaking-front/src/pages/Post/units/CommentForm.js
Labels: 🐛 bug, ♻️ Refactoring, ✨ Function

#146 feat: Skeleton 컴포넌트 구현
  breaking-front/src/components/Skeleton/Skeleton.js
  breaking-front/src/components/Skeleton/Skeleton.stories.js
  breaking-front/src/components/Skeleton/Skeleton.styles.js
Labels: ✨ Function, :lipstick: style

#151 feat: post write 페이지 카카오맵, 동영상/이미지 업로드 기능추가
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/public/index.html
  breaking-front/src/constants/palette.js
  breaking-front/src/pages/PostWrite/PostWrite.js
  breaking-front/src/pages/PostWrite/PostWrite.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteModal.js
  breaking-front/src/pages/PostWrite/units/PostWriteModal.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteSearchLocation.js
  breaking-front/src/pages/PostWrite/units/PostWriteSearchLocation.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteUploadMediaForm.js
  breaking-front/src/pages/PostWrite/units/PostWriteUploadMediaForm.styles.js
  breaking-front/src/styles/theme.js
  breaking-front/src/utils/parseAddressName.js
Labels: ✨ Function

#149 feat: 메인 피드 페이지 기능 추가
  breaking-front/src/App.js
  breaking-front/src/api/mainFeed.js
  breaking-front/src/assets/svg/top.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/Modal/Modal.js
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
  breaking-front/src/components/ScrollToTop/ScrollToTop.js
  breaking-front/src/components/ScrollToTop/ScrollToTop.stories.js
  breaking-front/src/components/ScrollToTop/ScrollToTop.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useMainFeedOption.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/mainFeedHandlers.js
  breaking-front/src/pages/MainFeed/MainFeed.js
  breaking-front/src/pages/MainFeed/MainFeed.styles.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/CommentForm.js
  breaking-front/src/utils/numberFormatter.js
  breaking-front/src/utils/timeFormatter.js
Labels: ♻️ Refactoring, ✨ Function

#154 feat: post write 페이지 데이터 백엔드로 넘기는 로직 추가
  breaking-front/src/api/postWrite.js
  breaking-front/src/constants/message.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/mocks/postWriteHandlers.js
  breaking-front/src/pages/PostWrite/PostWrite.js
  breaking-front/src/pages/PostWrite/PostWrite.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteSearchLocation.js
  breaking-front/src/pages/PostWrite/units/PostWriteSearchLocation.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteUploadMediaForm.js
Labels: ✨ Function

#156 feat: Post 페이지를 백엔드와 연결하는 테스트 진행
  breaking-front/.storybook/preview.js
  breaking-front/src/App.js
  breaking-front/src/api/financial.js
  breaking-front/src/api/post.js
  breaking-front/src/assets/svg/default_thumbnail_image.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.stories.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useTransaction.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/dummyData/users.js
  breaking-front/src/mocks/financialHandlers.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/mocks/mainFeedHandlers.js
  breaking-front/src/pages/Financial/Financial.js
  breaking-front/src/pages/Financial/Financial.styles.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Carousel.js
  breaking-front/src/pages/Post/units/Carousel.styles.js
  breaking-front/src/providers/UserInformationProvider.js
Labels: 🧪 Test, ♻️ Refactoring, ✨ Function

#161 feat: 로그아웃 기능 추가
  breaking-front/src/api/login.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/hooks/queries/useLogout.js
  breaking-front/src/mocks/signInHandlers.js
  breaking-front/src/providers/UserInformationProvider.js
Labels: ✨ Function

#163 feat: 페이지에 로딩 기능 추가
  breaking-front/src/hooks/queries/useFollowList.js
  breaking-front/src/hooks/queries/useFollowerList.js
  breaking-front/src/hooks/queries/useFollowingList.js
  breaking-front/src/mocks/postWriteHandlers.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/PostWrite/PostWrite.js
  breaking-front/src/pages/PostWrite/PostWrite.styles.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.styles.js
Labels: ✨ Function

#165 feat: 프로필 수정 페이지 API Sheet에 맞게 변경 및 탈퇴 기능 추가
  breaking-front/src/api/profile.js
  breaking-front/src/components/Modal/Modal.js
  breaking-front/src/components/Modal/Modal.styles.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useJWTValidate.js
  breaking-front/src/hooks/queries/useProfileDetailData.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/mocks/profileSettingHandlers.js
  breaking-front/src/pages/Financial/Financial.js
  breaking-front/src/pages/ProfileEdit/ProfileEdit.js
  breaking-front/src/pages/ProfileEdit/ProfileEdit.styles.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/providers/UserInformationProvider.js
Labels: ♻️ Refactoring, ✨ Function

#173 fix: 테스트 시 나오는 오류 수정
  breaking-front/src/api/post.js
  breaking-front/src/assets/svg/comment.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/ProfileImage/ProfileImage.js
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
  breaking-front/src/hooks/queries/useLogout.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/mainFeedHandlers.js
  breaking-front/src/pages/MainFeed/MainFeed.js
  breaking-front/src/pages/MainFeed/MainFeed.styles.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/Comment.styles.js
  breaking-front/src/pages/Post/units/CommentForm.js
  breaking-front/src/pages/Post/units/CommentForm.styles.js
  breaking-front/src/providers/UserInformationProvider.js
  breaking-front/src/styles/GlobalStyle.js
Labels: 🐛 bug

#168 fix: profile 팔로잉 팔로워 모달 문제 해결
  breaking-front/src/api/profile.js
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/components/FollowCard/FollowCard.styles.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.styles.js
  breaking-front/src/pages/Profile/units/ProfileFollowModal.js
Labels: 🐛 bug, ✨ Function

#184 feat: access token 만료시 refresh token을 이용해 재발급
  breaking-front/src/api/api.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/signInHandlers.js
Labels: ✨ Function

#178 feat: useInfiniteScroll custom hook 구현
  breaking-front/src/api/post.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/useInfiniteScroll.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/pages/MainFeed/MainFeed.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/MediaModal.js
  breaking-front/src/pages/Post/units/MediaModal.styles.js
Labels: 🐛 bug, ✨ Function

#181 feat: utils 테스트 코드 작성
  breaking-front/src/__test__/utils/ImageUrlConverter.test.js
  breaking-front/src/__test__/utils/numberFormatter.test.js
  breaking-front/src/__test__/utils/parseAddressName.test.js
  breaking-front/src/__test__/utils/timeFormatter.test.js
  breaking-front/src/mocks/server.js
  breaking-front/src/setupTests.js
  breaking-front/src/utils/parseAddressName.js
Labels: 🧪 Test

#187 feat: 새로운 Feed UI 구현
  breaking-front/src/api/post.js
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Tag/Tag.js
  breaking-front/src/components/Tag/Tag.stories.js
  breaking-front/src/components/Tag/Tag.styles.js
  breaking-front/src/components/Toggle/Toggle.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/postHandlers.js
Labels: :lipstick: style

#176 feat: postEdit 페이지를 생성한다.
  breaking-front/.eslintrc.js
  breaking-front/src/App.js
  breaking-front/src/api/postEdit.js
  breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.js
  breaking-front/src/components/PostWriteCommonForm/PostWriteCommonForm.styles.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteModal.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteModal.styles.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteSearchLocation.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteSearchLocation.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/mocks/postEditHandlers.js
  breaking-front/src/pages/PostEdit/PostEdit.js
  breaking-front/src/pages/PostEdit/PostEdit.styles.js
  breaking-front/src/pages/PostEdit/hooks/usePostEditMutation.js
  breaking-front/src/pages/PostWrite/PostWrite.js
  breaking-front/src/pages/PostWrite/PostWrite.styles.js
  breaking-front/src/pages/PostWrite/components/PostWriteUploadMediaForm.js
  breaking-front/src/pages/PostWrite/components/PostWriteUploadMediaForm.styles.js
  breaking-front/src/pages/PostWrite/hooks/usePostWriteMutation.js
  breaking-front/src/utils/extractHashtag.js
Labels: ✨ Function

#193 feat: 카카오 서버 데이터에 client_secret 필드값 추가
  breaking-front/src/pages/SocialLogin/Redirect/KakaoRedirect.js
Labels: 🐛 bug

#194 feat: extractHashtag 테스트코드 작성
  breaking-front/src/__test__/utils/extractHashtag.test.js
  breaking-front/src/utils/extractHashtag.js
Labels: ✨ Function

#191 feat: 팔로우 팔로워 모달에 인피니티 스크롤링 구현
  breaking-front/src/api/profile.js
  breaking-front/src/components/InfiniteTargetDiv/InfiniteTargetDiv.js
  breaking-front/src/components/InfiniteTargetDiv/InfiniteTargetDiv.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useFollowerList.js
  breaking-front/src/hooks/queries/useFollowingList.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/components/FollowCardList/FollowCardList.js
  breaking-front/src/pages/Profile/components/ProfileFollowButton/ProfileFollowButton.js
  breaking-front/src/pages/Profile/components/ProfileFollowButton/ProfileFollowButton.styles.js
  breaking-front/src/pages/Profile/components/ProfileFollowModal/ProfileFollowModal.js
  breaking-front/src/pages/Profile/components/ProfileFollowModal/ProfileFollowModal.styles.js
  breaking-front/src/pages/Profile/components/ProfileTabPanel/ProfileTabPanel.js
  breaking-front/src/pages/Profile/components/ProfileTabPanel/ProfileTabPanel.styles.js
  breaking-front/src/pages/Profile/hooks/mutations/useFollow.js
  breaking-front/src/pages/Profile/hooks/mutations/useUnFollow.js
  breaking-front/src/pages/Profile/hooks/queries/useFollowerList.js
  breaking-front/src/pages/Profile/hooks/queries/useFollowingList.js
  breaking-front/src/pages/Profile/hooks/queries/useProfile.js
  breaking-front/src/pages/Profile/hooks/queries/useProfileBookmarkedPost.js
  breaking-front/src/pages/Profile/hooks/queries/useProfileBoughtPost.js
  breaking-front/src/pages/Profile/hooks/queries/useProfileWrittenPost.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.js
  breaking-front/src/pages/Profile/units/ProfileFollowModal.js
Labels: ♻️ Refactoring, ✨ Function

#201 fix: SignUp 페이지 전화번호 입력 오류 수정 및 hook 분리
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/constants/message.js
  breaking-front/src/pages/ProfileEdit/ProfileEdit.js
  breaking-front/src/pages/ProfileEdit/hooks/mutations/useProfileEdit.js
  breaking-front/src/pages/ProfileEdit/hooks/mutations/useProfileWithdrawal.js
  breaking-front/src/pages/ProfileEdit/hooks/queries/useProfileDetailData.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SignUp/hooks/mutations/useSignUp.js
Labels: 🐛 bug, ♻️ Refactoring

#205 feat: SearchFilter 컴포넌트 구현
  breaking-front/src/components/SearchFilter/SearchFilter.js
  breaking-front/src/components/SearchFilter/SearchFilter.styles.js
  breaking-front/src/pages/MainFeed/MainFeed.js
  breaking-front/src/pages/MainFeed/MainFeed.styles.js
Labels: ♻️ Refactoring, ✨ Function

#207 feat: NoData 컴포넌트 구현
  breaking-front/src/assets/svg/no_data.svg
  breaking-front/src/components/NoData/NoData.js
  breaking-front/src/components/NoData/NoData.stories.js
  breaking-front/src/components/NoData/NoData.styles.js
Labels: ✨ Function

#216 fix: Header 컴포넌트 잘려 보이는 문제 수정
  breaking-front/src/components/Header/Header.styles.js
Labels: 🐛 bug

#212 refactor: followcard를 재사용하게 만든다.
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/pages/Profile/components/FollowCardList/FollowCardList.js
  breaking-front/src/pages/Profile/components/ProfileFollowModal/ProfileFollowModal.js
  breaking-front/src/pages/Profile/hooks/queries/useFollowerList.js
  breaking-front/src/pages/Profile/hooks/queries/useFollowingList.js
Labels: 🐛 bug, ♻️ Refactoring

#214 feat: modal창이 오픈되었을때 배경이 스크롤되지 않는다.
  breaking-front/src/components/Modal/Modal.js
Labels: ✨ Function

#208 feat: 검색 결과 페이지 UI 작성
  breaking-front/src/App.js
  breaking-front/src/components/FollowButton/FollowButton.js
  breaking-front/src/components/FollowButton/FollowButton.styles.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Search/SearchHashtag/SearchHashtag.js
  breaking-front/src/pages/Search/SearchHashtag/SearchHashtag.styles.js
  breaking-front/src/pages/Search/SearchPost/SearchPost.js
  breaking-front/src/pages/Search/SearchPost/SearchPost.styles.js
  breaking-front/src/pages/Search/SearchUnified/SearchUnified.js
  breaking-front/src/pages/Search/SearchUnified/SearchUnified.styles.js
  breaking-front/src/pages/Search/SearchUnified/components/UserCard/UserCard.js
  breaking-front/src/pages/Search/SearchUnified/components/UserCard/UserCard.styles.js
  breaking-front/src/pages/Search/SearchUser/SearchUser.js
  breaking-front/src/pages/Search/SearchUser/SearchUser.styles.js
  breaking-front/src/pages/Search/SearchUser/components/SearchUserResultCard.js
  breaking-front/src/pages/Search/SearchUser/components/SearchUserResultCard.styles.js
  breaking-front/src/pages/Search/components/SearchHeader/SearchHeader.js
  breaking-front/src/pages/Search/components/SearchHeader/SearchHeader.styles.js
Labels: ✨ Function, :lipstick: style

#218 refactor: follow unfollow hook을 공통 hook로 추출
  breaking-front/src/components/FollowButton/FollowButton.js
  breaking-front/src/hooks/mutations/useFollow.js
  breaking-front/src/hooks/mutations/useUnFollow.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/hooks/mutations/useFollow.js
  breaking-front/src/pages/Profile/hooks/mutations/useUnFollow.js
Labels: 🚑 Hot-Fix, ♻️ Refactoring

#189 feat: 입출금 페이지 UI 및 기능 구현
  breaking-front/src/api/financial.js
  breaking-front/src/constants/palette.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useTransaction.js
  breaking-front/src/mocks/financialHandlers.js
  breaking-front/src/pages/Financial/Financial.js
  breaking-front/src/pages/Financial/Financial.styles.js
  breaking-front/src/pages/Financial/components/Transaction/Transaction.js
  breaking-front/src/pages/Financial/components/Transaction/Transaction.styles.js
  breaking-front/src/pages/Financial/components/TransactionBox/TransactionBox.js
  breaking-front/src/pages/Financial/components/TransactionBox/TransactionBox.styles.js
  breaking-front/src/pages/Financial/components/TransactionForm/TransactionForm.js
  breaking-front/src/pages/Financial/components/TransactionForm/TransactionForm.styles.js
  breaking-front/src/pages/Financial/hooks/queries/useTransaction.js
  breaking-front/src/pages/Financial/hooks/useDeposit.js
  breaking-front/src/pages/Financial/hooks/useWithdraw.js
Labels: ✨ Function, :lipstick: style

#223 feat: 세부 조회 페이지에서 구매자 리스트 및 좋아요 리스트 Modal 추가
  breaking-front/src/__test__/utils/LikeCount.test.js
  breaking-front/src/api/post.js
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/components/FollowCard/FollowCard.styles.js
  breaking-front/src/hooks/mutations/useFollow.js
  breaking-front/src/hooks/mutations/useUnFollow.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/components/PostBoughtListModal/PostBoughtListModal.js
  breaking-front/src/pages/Post/components/PostBoughtListModal/PostBoughtListModal.styles.js
  breaking-front/src/pages/Post/components/PostLikeListModal/PostLikeListModal.js
  breaking-front/src/pages/Post/components/PostLikeListModal/PostLikeListModal.styles.js
  breaking-front/src/pages/Post/components/PurchaseButton/PurchaseButton.js
  breaking-front/src/pages/Post/hooks/queries/usePostBoughtList.js
  breaking-front/src/pages/Post/hooks/queries/usePostLikeList.js
  breaking-front/src/utils/LikeCount.js
Labels: ♻️ Refactoring, ✨ Function

#224 refactor: 새로운 Feed Skeleton UI 구현
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Skeleton/Skeleton.js
  breaking-front/src/components/Skeleton/Skeleton.styles.js
Labels: :lipstick: style

#225 feat: public 폴더를 설정한다.
  breaking-front/package.json
  breaking-front/public/breaking_logo.png
  breaking-front/public/favicon.ico
  breaking-front/public/index.html
  breaking-front/public/logo192.png
  breaking-front/public/logo512.png
  breaking-front/public/manifest.json
Labels: ✨ Function

#226 feat: NotFound 페이지 생성
  breaking-front/src/pages/NotFound/NotFound.js
  breaking-front/src/pages/NotFound/NotFound.styles.js
Labels: ✨ Function

#227 feat: PrivateRoute 구현 및 적용
  breaking-front/src/App.js
  breaking-front/src/PrivateRoute.js
  breaking-front/src/pages/SignUp/SignUp.js
Labels: ✨ Function

#229 feat: 검색 결과 페이지에 searchfilter를 추가한다.
  breaking-front/src/api/search.js
  breaking-front/src/components/SearchFilter/SearchFilter.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/useInfiniteScroll.js
  breaking-front/src/pages/Search/SearchHashtag/SearchHashtag.js
  breaking-front/src/pages/Search/SearchHashtag/SearchHashtag.styles.js
  breaking-front/src/pages/Search/SearchPost/SearchPost.js
  breaking-front/src/pages/Search/SearchPost/SearchPost.styles.js
  breaking-front/src/pages/Search/hooks/queries/useSearch.js
  breaking-front/src/pages/Search/hooks/queries/useSearchHashtag.js
  breaking-front/src/pages/Search/hooks/queries/useSearchUser.js
Labels: ✨ Function, :lipstick: style

#230 feat: 공유기능 구현
  breaking-front/public/index.html
  breaking-front/src/assets/img/facebook.png
  breaking-front/src/assets/img/twitter.png
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/ShareModal/ShareModal.js
  breaking-front/src/components/ShareModal/ShareModal.stories.js
  breaking-front/src/components/ShareModal/ShareModal.styles.js
  breaking-front/src/pages/Post/components/ContentToggle/ContentToggle.js
  breaking-front/src/pages/SocialLogin/SocialLogin.js
Labels: ✨ Function

#232 feat: 비로그인시 팔로우 버튼을 띄워주지 않음
  breaking-front/src/components/FollowButton/FollowButton.js
  breaking-front/src/pages/Profile/components/FollowCardList/FollowCardList.js
  breaking-front/src/pages/Search/SearchUnified/SearchUnified.js
  breaking-front/src/pages/Search/SearchUnified/components/UserCard/UserCard.js
Labels: ✨ Function

#233 feat: 다운로드 기능 구현
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/src/api/post.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/pages/Post/components/PurchaseButton/PurchaseButton.js
  breaking-front/src/pages/Post/hooks/queries/usePostDownload.js
Labels: ✨ Function

#234 refactor: 컴포넌트 리팩토링
  breaking-front/src/components/Line/Line.styles.js
  breaking-front/src/components/ShareModal/ShareModal.js
  breaking-front/src/components/Tag/Tag.js
Labels: ♻️ Refactoring

#235 refactor: 예외 처리
  breaking-front/src/App.js
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/usePost.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/components/Comment/Comment.js
  breaking-front/src/pages/Post/components/CommentForm/CommentForm.js
  breaking-front/src/pages/Post/components/ContentToggle/ContentToggle.js
  breaking-front/src/pages/Post/components/PurchaseButton/PurchaseButton.js
  breaking-front/src/pages/PostEdit/PostEdit.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/hooks/queries/useProfile.js
Labels: ♻️ Refactoring
