Repository Breaking-Dope/breaking-frontend, pull requests merged in 2022-09, with the labels that each got.

#238 hotfix: 1.0.1
  breaking-front/package.json
  breaking-front/public/index.html
  breaking-front/src/api/api.js
  breaking-front/src/api/login.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteSearchLocation.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/components/Carousel/Carousel.js
  breaking-front/src/pages/Post/components/Comment/Comment.js
  breaking-front/src/pages/Post/components/CommentForm/CommentForm.js
  breaking-front/src/pages/Post/components/CommentList/CommentList.js
  breaking-front/src/pages/Post/components/PurchaseButton/PurchaseButton.js
  breaking-front/src/pages/Post/hooks/mutations/useCommentReplyWrite.js
  breaking-front/src/pages/Post/hooks/mutations/useCommentWrite.js
  breaking-front/src/pages/Post/hooks/mutations/useDeleteComment.js
  breaking-front/src/pages/Post/hooks/mutations/usePostBuy.js
Labels: 🚑 Hot-Fix

#239 hotfix: v1.0.1
  breaking-front/package.json
  breaking-front/public/index.html
  breaking-front/src/api/api.js
  breaking-front/src/api/login.js
  breaking-front/src/components/PostWriteCommonForm/SearchLocation/PostWriteSearchLocation.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/components/Carousel/Carousel.js
  breaking-front/src/pages/Post/components/Comment/Comment.js
  breaking-front/src/pages/Post/components/CommentForm/CommentForm.js
  breaking-front/src/pages/Post/components/CommentList/CommentList.js
  breaking-front/src/pages/Post/components/PurchaseButton/PurchaseButton.js
  breaking-front/src/pages/Post/hooks/mutations/useCommentReplyWrite.js
  breaking-front/src/pages/Post/hooks/mutations/useCommentWrite.js
  breaking-front/src/pages/Post/hooks/mutations/useDeleteComment.js
  breaking-front/src/pages/Post/hooks/mutations/usePostBuy.js
Labels: 🚑 Hot-Fix

#246 feat: breaking map page UI 생성
  breaking-front/src/App.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/dummyData/mission.js
  breaking-front/src/pages/BreakingMission/MissionMap/MissionMap.js
  breaking-front/src/pages/BreakingMission/MissionMap/MissionMap.styles.js
  breaking-front/src/pages/BreakingMission/MissionMap/components/MissionMapMarker.js
  breaking-front/src/pages/BreakingMission/MissionMap/components/MissionMapMarker.styles.js
Labels: ✨ Function

#248 refactor: MediaFileToUrl util 추가
  breaking-front/src/__test__/utils/MediaFileToUrl.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/pages/Post/PostWrite/components/PostWriteUploadMediaForm.js
  breaking-front/src/utils/MediaFileToUrl.js
  breaking-front/src/utils/fileToBase64.js
Labels: ♻️ Refactoring, ✨ Function

#251 refactor: ProfileSettingForm 컴포넌트 리팩토링
  breaking-front/src/api/signUp.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.styles.js
  breaking-front/src/constants/message.js
  breaking-front/src/hooks/queries/useIsValidProfile.js
  breaking-front/src/pages/Authentication/SignUp/SignUp.js
  breaking-front/src/pages/Profile/ProfileEdit/ProfileEdit.js
Labels: 🗣️ Conversation, ♻️ Refactoring

#253 feat: 숨김 기능 추가
  breaking-front/src/api/post.js
  breaking-front/src/assets/svg/hide.svg
  breaking-front/src/assets/svg/hided.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Tag/Tag.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/postHandlers.js
  breaking-front/src/pages/Post/Post/Post.js
  breaking-front/src/pages/Post/Post/components/ContentToggle/ContentToggle.js
  breaking-front/src/pages/Post/Post/hooks/mutations/usePostDeactivatePurchase.js
  breaking-front/src/pages/Post/Post/hooks/mutations/usePostHide.js
  breaking-front/src/pages/Post/Post/hooks/mutations/usePostShow.js
Labels: ♻️ Refactoring, ✨ Function

#260 refactor: urlToFile util 삭제 및 MediaFileToUrl 테스트 코드 이름 변경
  breaking-front/src/__test__/utils/MediaFileToUrl.test.js
  breaking-front/src/utils/urlToFile.js
Labels: ⛔ Useless, ♻️ Refactoring

#267 feat: 브레이킹 미션 페이지 UI 구현
  breaking-front/src/App.js
  breaking-front/src/api/breakingMission.js
  breaking-front/src/components/MissionFeed/MissionFeed.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/breakingMissionHandlers.js
  breaking-front/src/mocks/dummyData/mission.js
  breaking-front/src/pages/BreakingMission/MissionPost/MissionPost.js
  breaking-front/src/pages/BreakingMission/MissionPost/MissionPost.styles.js
  breaking-front/src/pages/BreakingMission/MissionPost/components/MissionPostFeed/MissionPostFeed.js
  breaking-front/src/pages/BreakingMission/MissionPost/components/MissionPostFeed/MissionPostFeed.styles.js
  breaking-front/src/pages/BreakingMission/MissionPost/components/MissionToggle/MissionToggle.js
  breaking-front/src/pages/BreakingMission/MissionPost/components/MissionToggle/MissionToggle.styles.js
  breaking-front/src/pages/BreakingMission/MissionPost/components/SubmitButton/SubmitButton.js
  breaking-front/src/pages/BreakingMission/MissionPost/hooks/queries/useMissionPost.js
  breaking-front/src/pages/BreakingMission/MissionPost/hooks/queries/useMissionPostFeed.js
  breaking-front/src/pages/Post/Post/Post.js
  breaking-front/src/pages/Post/Post/Post.styles.js
  breaking-front/src/pages/Post/Post/components/ContentToggle/ContentToggle.js
Labels: :lipstick: style
