Repository Breaking-Dope/breaking-frontend, pull requests merged in 2022-07, with the labels that each got.

#23 feat: 카카오 로그인 구현
  breaking-front/.gitignore
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/public/index.html
  breaking-front/src/App.js
  breaking-front/src/Pages/SocialLogin/KakaoRedirect.js
  breaking-front/src/Pages/SocialLogin/SocialLogin.js
  breaking-front/src/api/login.js
  breaking-front/src/constants/path.js
Labels: 🗣️ Conversation, ✨ Function

#27 fix: 남아있는 Pages 폴더 삭제
  breaking-front/src/Pages/SocialLogin/KakaoRedirect.js
  breaking-front/src/Pages/SocialLogin/SocialLogin.js
Labels: 🚑 Hot-Fix

#28 feat: 구글 로그인 기능 추가
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/src/App.js
  breaking-front/src/pages/SocialLogin/SocialLogin.js
Labels: ✨ Function

#31 feat: 로그인 버튼 UI 구현
  breaking-front/.gitignore
  breaking-front/src/assets/svg/app_store.svg
  breaking-front/src/assets/svg/google_login.svg
  breaking-front/src/assets/svg/google_play.svg
  breaking-front/src/assets/svg/kakao_login.svg
  breaking-front/src/components/MobileDownloadButton/MobileDownload.stories.js
  breaking-front/src/components/MobileDownloadButton/MobileDownload.styles.js
  breaking-front/src/components/MobileDownloadButton/MobileDownloadButton.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.stories.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.styles.js
Labels: :lipstick: style, 📕 storybook

#33 fix: svg에서 pattern의 id값을 고유한 값으로 변경한다
  breaking-front/src/assets/svg/app_store.svg
  breaking-front/src/assets/svg/google_login.svg
  breaking-front/src/assets/svg/google_play.svg
  breaking-front/src/assets/svg/kakao_login.svg
Labels: 🐛 bug, 🚑 Hot-Fix

#35 style: Line UI 추가
  breaking-front/src/components/Line/Line.js
  breaking-front/src/components/Line/Line.stories.js
  breaking-front/src/components/Line/Line.styles.js
Labels: :lipstick: style, 📕 storybook

#30 feat: 회원가입 페이지 로직 구현
  breaking-front/src/App.js
  breaking-front/src/api/signUp.js
  breaking-front/src/assets/svg/default-profile-image.svg
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/useIsValidEmail.js
  breaking-front/src/hooks/useIsValidNickname.js
  breaking-front/src/hooks/useIsValidPhoneNumber.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SignUp/SignUp.styles.js
  breaking-front/src/utils/fileToBase64.js
Labels: ✨ Function

#36 refactor: 컴포넌트 절대경로로 수정
  breaking-front/src/components/Button/Button.js
  breaking-front/src/components/Button/Button.stories.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.stories.js
  breaking-front/src/components/Input/Input.js
  breaking-front/src/components/Input/Input.stories.js
  breaking-front/src/components/MobileDownloadButton/MobileDownload.stories.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.stories.js
  breaking-front/src/setupTests.js
Labels: 🐛 bug, ♻️ Refactoring

#44 fix: 로그인 페이지 버튼 크기가 부모요소에 따라 가변적으로 변하는 현상 수정
  breaking-front/src/components/MobileDownloadButton/MobileDownload.styles.js
  breaking-front/src/components/MobileDownloadButton/MobileDownloadButton.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.js
  breaking-front/src/components/SocialLoginButton/SocialLoginButton.styles.js
Labels: 🐛 bug, :lipstick: style, 📕 storybook

#45 feat: SignUpInput 컴포넌트 구현
  breaking-front/src/components/SignUpInput/SignUpInput.js
  breaking-front/src/components/SignUpInput/SignUpInput.stories.js
  breaking-front/src/components/SignUpInput/SignUpInput.styles.js
Labels: :lipstick: style, 📕 storybook

#47 feat: Layout 컴포넌트 구현
  breaking-front/src/App.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/Layout/Layout.styles.js
Labels: :lipstick: style

#51 fix: Header z-index 값 수정
  breaking-front/src/components/Header/Header.styles.js
Labels: :lipstick: style

#48 feat: 로그인 페이지 UI 생성
  breaking-front/src/assets/img/breaking-logo.png
  breaking-front/src/pages/SocialLogin/SocialLogin.js
  breaking-front/src/pages/SocialLogin/SocialLogin.style.js
Labels: ✨ Function, :lipstick: style

#53 feat: Button 컴포넌트 isSelected prop 추가
  breaking-front/src/components/Button/Button.js
  breaking-front/src/components/Button/Button.stories.js
  breaking-front/src/components/Button/Button.styles.js
Labels: ✨ Function, 📕 storybook

#54 feat: 로그인시에 받은 토큰을 서버로 전송한다
  breaking-front/src/api/api.js
  breaking-front/src/api/login.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SocialLogin/KakaoRedirect.js
  breaking-front/src/pages/SocialLogin/SocialLogin.js
Labels: ✨ Function

#56 style: 판매중, 판매완료, 단독 라벨 버튼을 구현
  breaking-front/src/components/Button/Button.stories.js
  breaking-front/src/components/Button/Button.styles.js
Labels: :lipstick: style, 📕 storybook

#58 feat: 유저 이미지 컴포넌트를 생성한다
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.styles.js
  breaking-front/src/components/UserImage/UserImage.js
  breaking-front/src/components/UserImage/UserImage.stories.js
  breaking-front/src/components/UserImage/UserImage.styles.js
Labels: :lipstick: style, 📕 storybook

#60 fix: Input 컴포넌트에 ref 추가하여 DOM 접근 하도록 수정
  breaking-front/src/components/Input/Input.js
Labels: 🐛 bug

#61 fix: displayName 추가, SignUpInput에 forwardRef 추가
  breaking-front/src/components/Input/Input.js
  breaking-front/src/components/SignUpInput/SignUpInput.js
Labels: 🐛 bug

#55 feat: 회원가입 UI 구현
  breaking-front/src/api/signUp.js
  breaking-front/src/assets/svg/default-profile-image.svg
  breaking-front/src/assets/svg/x-mark.svg
  breaking-front/src/constants/message.js
  breaking-front/src/constants/regexp.js
  breaking-front/src/hooks/useInputs.js
  breaking-front/src/hooks/useIsValidEmail.js
  breaking-front/src/hooks/useIsValidNickname.js
  breaking-front/src/hooks/useIsValidPhoneNumber.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SignUp/SignUp.styles.js
Labels: ✨ Function, :lipstick: style

#62 feat: 토글 컴포넌트를 구현한다.
  breaking-front/.storybook/preview.js
  breaking-front/src/assets/svg/money.svg
  breaking-front/src/assets/svg/mypage.svg
  breaking-front/src/assets/svg/setting.svg
  breaking-front/src/components/Toggle/Toggle.js
  breaking-front/src/components/Toggle/Toggle.stories.js
  breaking-front/src/components/Toggle/Toggle.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/styles/GlobalStyle.js
  breaking-front/src/styles/theme.js
Labels: :lipstick: style, 📕 storybook

#65 fix: 컴포넌트 버그 수정
  breaking-front/src/components/Button/Button.js
  breaking-front/src/components/Input/Input.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/Line/Line.js
Labels: 🐛 bug, ✨ Function, :lipstick: style, 📕 storybook

#68 style: Feed UI 컴포넌트를 구현한다(2)
  breaking-front/src/assets/svg/bookmark.svg
  breaking-front/src/assets/svg/bookmarked.svg
  breaking-front/src/assets/svg/etc.svg
  breaking-front/src/assets/svg/like.svg
  breaking-front/src/assets/svg/liked.svg
  breaking-front/src/assets/svg/location.svg
  breaking-front/src/components/Button/Button.styles.js
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Feed/Feed.styles.js
Labels: 🗣️ Conversation, :lipstick: style, 📕 storybook

#66 feat: Header 컴포넌트에 프로필 토글 추가
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.styles.js
  breaking-front/src/components/Toggle/Toggle.js
  breaking-front/src/components/Toggle/Toggle.stories.js
  breaking-front/src/components/Toggle/Toggle.styles.js
Labels: ✨ Function, :lipstick: style

#81 fix: UserImage에서 디폴트 이미지가 올바르게 보이지 않는 버그 수정 및 UserImage의 명칭 변경
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.styles.js
  breaking-front/src/components/ProfileImage/ProfileImage.js
  breaking-front/src/components/ProfileImage/ProfileImage.stories.js
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
  breaking-front/src/components/UserImage/UserImage.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SignUp/SignUp.styles.js
Labels: 🐛 bug, :lipstick: style

#79 feat: FollowCard 컴포넌트 구현
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/components/FollowCard/FollowCard.stories.js
  breaking-front/src/components/FollowCard/FollowCard.styles.js
  breaking-front/src/constants/palette.js
Labels: :lipstick: style, 📕 storybook

#85 feat: Modal 컴포넌트 구현
  breaking-front/src/components/Modal/Modal.js
  breaking-front/src/components/Modal/Modal.stories.js
  breaking-front/src/components/Modal/Modal.styles.js
  breaking-front/src/components/ScrollBar/ScrollBar.js
  breaking-front/src/constants/palette.js
  breaking-front/src/styles/theme.js
Labels: :lipstick: style, 📕 storybook

#86 feat: 백엔드와 로그인 테스트 작업
  breaking-front/src/App.js
  breaking-front/src/api/api.js
  breaking-front/src/api/login.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/SocialLogin/Redirect/GoogleRedirect.js
  breaking-front/src/pages/SocialLogin/Redirect/KakaoRedirect.js
  breaking-front/src/pages/SocialLogin/SocialLogin.js
Labels: ✨ Function

#84 feat: filter 컴포넌트 UI 구현
  breaking-front/src/assets/svg/filter.svg
  breaking-front/src/components/Filter/Filter.js
  breaking-front/src/components/Filter/Filter.stories.js
  breaking-front/src/components/Filter/Filter.styles.js
Labels: :lipstick: style, 📕 storybook

#88 feat: tabs 컴포넌트 구현한다.
  breaking-front/src/components/Tabs/Tabs.js
  breaking-front/src/components/Tabs/Tabs.stories.js
  breaking-front/src/components/Tabs/Tabs.styles.js
Labels: :lipstick: style, 📕 storybook

#89 refactor: 회원가입 로직 변경
  breaking-front/src/api/signUp.js
  breaking-front/src/constants/message.js
  breaking-front/src/hooks/queries/useIsValidProfile.js
  breaking-front/src/hooks/useIsValidEmail.js
  breaking-front/src/hooks/useIsValidNickname.js
  breaking-front/src/hooks/useIsValidPhoneNumber.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SignUp/SignUp.styles.js
  breaking-front/src/utils/fileToBase64.js
Labels: ♻️ Refactoring

#93 refactor: Feed 컴포넌트 리팩토링
  breaking-front/src/assets/svg/edit.svg
  breaking-front/src/assets/svg/etc.svg
  breaking-front/src/assets/svg/hide.svg
  breaking-front/src/assets/svg/remove.svg
  breaking-front/src/assets/svg/share.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/components/Feed/Feed.styles.js
Labels: ♻️ Refactoring, ✨ Function, 📕 storybook

#92 feat: filter 구조를 변경한다
  breaking-front/src/components/Filter/Filter.js
  breaking-front/src/components/Filter/Filter.stories.js
  breaking-front/src/components/Filter/Filter.styles.js
Labels: ✨ Function, :lipstick: style, 📕 storybook

#97 fix: ProfileImage 버그 수정 및 xlarge 크기 변경
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
Labels: 🐛 bug, :lipstick: style

#96 feat: 프로필 페이지 UI를 만든다
  breaking-front/src/App.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/Profile.styles.js
  breaking-front/src/styles/GlobalStyle.js
Labels: :lipstick: style

#99 chore: axios 요청 시 로그인한 유저는 header에 JWTtoken을 넣어 전송하도록 설정
  breaking-front/src/api/api.js
Labels: ✨ Function

#102 refactor: PATH를 PAGE_PATH와 API_PATH로 분리
  breaking-front/src/App.js
  breaking-front/src/api/login.js
  breaking-front/src/api/signUp.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Layout/Layout.js
  breaking-front/src/components/Toggle/Toggle.stories.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SocialLogin/Redirect/GoogleRedirect.js
  breaking-front/src/pages/SocialLogin/Redirect/KakaoRedirect.js
Labels: ♻️ Refactoring

#100 refactor: 회원가입 로직을 컴포넌트로 분리한다.
  breaking-front/src/components/SignUpForm/SignUpForm.js
  breaking-front/src/components/SignUpForm/SignUpForm.styles.js
  breaking-front/src/pages/SignUp/SignUp.js
Labels: ♻️ Refactoring, ✨ Function

#104 refactor: SignUpForm 및 SignUpInput 컴포넌트 명칭 변경
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.styles.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.stories.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.styles.js
  breaking-front/src/components/SignUpInput/SignUpInput.js
  breaking-front/src/pages/SignUp/SignUp.js
Labels: ♻️ Refactoring

#107 fix: 컴포넌트의 tabList의 chidren이 한개일시에 랜더링이 안되는 버그수정
  breaking-front/src/components/Tabs/Tabs.js
  breaking-front/src/components/Tabs/Tabs.stories.js
Labels: 🐛 bug

#109 fix: tabs 컴포넌트 children관련 버그 추가
  breaking-front/src/components/Tabs/Tabs.js
  breaking-front/src/components/Tabs/Tabs.stories.js
Labels: 🐛 bug

#112 feat: 프로필 페이지 기능추가
  breaking-front/src/App.js
  breaking-front/src/api/profile.js
  breaking-front/src/components/FollowCard/FollowCard.js
  breaking-front/src/components/SignUpForm/SignUpForm.js
  breaking-front/src/components/SignUpForm/SignUpForm.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useFollowList.js
  breaking-front/src/hooks/queries/useProfile.js
  breaking-front/src/hooks/queries/useProfilePost.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/Profile.styles.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.styles.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.styles.js
Labels: ✨ Function

#105 feat: 프로필 수정 페이지 로직 구현
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/src/App.js
  breaking-front/src/api/profileEdit.js
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useProfileDetailData.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/mocks/worker.js
  breaking-front/src/pages/ProfileEdit/ProfileEdit.js
  breaking-front/src/pages/ProfileEdit/ProfileEdit.styles.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/utils/urlToFile.js
Labels: ✨ Function

#115 feat: 유저정보를 전역 state에 저장한다
  breaking-front/src/App.js
  breaking-front/src/api/signUp.js
  breaking-front/src/components/Header/Header.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useJWTValidate.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SignUp/SignUp.js
  breaking-front/src/pages/SocialLogin/Redirect/GoogleRedirect.js
  breaking-front/src/pages/SocialLogin/Redirect/KakaoRedirect.js
  breaking-front/src/providers/UserInformationProvider.js
Labels: ✨ Function

#114 fix: 컴포넌트 버그 수정
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.styles.js
  breaking-front/src/components/Filter/Filter.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingInput.stories.js
  breaking-front/src/components/SignUpForm/SignUpForm.js
  breaking-front/src/components/SignUpForm/SignUpForm.styles.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/pages/SocialLogin/SocialLogin.js
  breaking-front/src/pages/SocialLogin/SocialLogin.styles.js
Labels: 🐛 bug, ♻️ Refactoring

#119 fix: 컴포넌트 변경사항 수정
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/components/Feed/Feed.stories.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.js
  breaking-front/src/pages/SignUp/SignUp.js
Labels: ♻️ Refactoring

#126 feat: modal의 기능을 추가한다
  breaking-front/src/api/profile.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileFollowButton.js
Labels: ✨ Function

#122 feat: MainFeed 페이지 구현
  breaking-front/src/App.js
  breaking-front/src/api/mainFeed.js
  breaking-front/src/assets/svg/pen.svg
  breaking-front/src/components/Feed/Feed.js
  breaking-front/src/hooks/queries/useMainFeedOption.js
  breaking-front/src/mocks/handlers.js
  breaking-front/src/mocks/mainFeedHandlers.js
  breaking-front/src/pages/MainFeed/MainFeed.js
  breaking-front/src/pages/MainFeed/MainFeed.styles.js
Labels: ✨ Function, :lipstick: style

#127 feat: dummy data 구조화작업
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/mocks/dummyData/users.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/mocks/signInHandlers.js
Labels: 🧪 Test, ✨ Function

#133 feat: pretendard 폰트 추가
  breaking-front/src/styles/GlobalStyle.js
  breaking-front/src/styles/fonts/Pretendard-Light.woff
  breaking-front/src/styles/fonts/Pretendard-Medium.woff
  breaking-front/src/styles/fonts/Pretendard-Regular.woff
  breaking-front/src/styles/fonts/Pretendard-SemiBold.woff
Labels: ✨ Function, :lipstick: style

#132 feat: 첫 방문시에 jwt 토큰이 유효한지 판단해 자동 로그인을 한다
  breaking-front/src/providers/UserInformationProvider.js
Labels: ✨ Function

#135 refactor: api sheet에 따른 path 추가 및 변수명 통일
  breaking-front/src/api/profile.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/profileHandlers.js
Labels: ♻️ Refactoring

#129 feat: 제보글 상세 페이지 구현
  breaking-front/src/App.js
  breaking-front/src/assets/svg/back.svg
  breaking-front/src/assets/svg/block.svg
  breaking-front/src/assets/svg/carousel_left.svg
  breaking-front/src/assets/svg/carousel_right.svg
  breaking-front/src/assets/svg/chat.svg
  breaking-front/src/assets/svg/comment.svg
  breaking-front/src/assets/svg/default_profile_image.svg
  breaking-front/src/assets/svg/down-arrow.svg
  breaking-front/src/assets/svg/drop_down.svg
  breaking-front/src/assets/svg/drop_up.svg
  breaking-front/src/assets/svg/slide_dot.svg
  breaking-front/src/assets/svg/slide_dot_fill.svg
  breaking-front/src/assets/svg/small_bookmark.svg
  breaking-front/src/assets/svg/small_bookmarked.svg
  breaking-front/src/assets/svg/small_logo.svg
  breaking-front/src/assets/svg/x_mark.svg
  breaking-front/src/components/Header/Header.js
  breaking-front/src/components/Header/Header.styles.js
  breaking-front/src/components/Modal/Modal.js
  breaking-front/src/components/ProfileImage/ProfileImage.styles.js
  breaking-front/src/components/ProfileSettingForm/ProfileSettingForm.js
  breaking-front/src/constants/path.js
  breaking-front/src/mocks/dummyData/contents.js
  breaking-front/src/pages/Post/Post.js
  breaking-front/src/pages/Post/Post.styles.js
  breaking-front/src/pages/Post/units/Carousel.js
  breaking-front/src/pages/Post/units/Carousel.styles.js
  breaking-front/src/pages/Post/units/Comment.js
  breaking-front/src/pages/Post/units/Comment.styles.js
  breaking-front/src/pages/Post/units/CommentForm.js
  breaking-front/src/pages/Post/units/CommentForm.styles.js
  breaking-front/src/pages/Post/units/MediaModal.js
  breaking-front/src/pages/Post/units/MediaModal.styles.js
Labels: ✨ Function, :lipstick: style

#137 feat: profile 페이지 기능 추가
  breaking-front/src/api/profile.js
  breaking-front/src/constants/path.js
  breaking-front/src/hooks/queries/useProfileBookmarkedPost.js
  breaking-front/src/hooks/queries/useProfileBoughtPost.js
  breaking-front/src/hooks/queries/useProfilePost.js
  breaking-front/src/hooks/queries/useProfileWrittenPost.js
  breaking-front/src/hooks/useCheckMyPage.js
  breaking-front/src/mocks/profileHandlers.js
  breaking-front/src/pages/Profile/Profile.js
  breaking-front/src/pages/Profile/units/ProfileTabPanel.js
Labels: ✨ Function

#139 feat: 게시글 작성 페이지 UI
  breaking-front/package-lock.json
  breaking-front/package.json
  breaking-front/src/App.js
  breaking-front/src/assets/svg/Plus.svg
  breaking-front/src/assets/svg/left_arrow_line.svg
  breaking-front/src/assets/svg/right_arrow_line.svg
  breaking-front/src/components/ScrollBar/ScrollBar.js
  breaking-front/src/constants/palette.js
  breaking-front/src/constants/path.js
  breaking-front/src/pages/PostWrite/PostWrite.js
  breaking-front/src/pages/PostWrite/PostWrite.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteUploadForm.styles.js
  breaking-front/src/pages/PostWrite/units/PostWriteUploadMediaForm.js
  breaking-front/src/styles/theme.js
Labels: :lipstick: style

#142 fix: tabs의 type name을 비교하는 대신 displayName을 지정 및 비교로 수정
  breaking-front/src/components/Tabs/Tabs.js
Labels: 🐛 bug, 🚑 Hot-Fix
